import Head from 'next/head';
import Image from 'next/image';
import { Grid } from '@mui/material';

export default function Home() {
  return (
    <>
      <Head>
        <title>Jobly</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid
        container
        direction='column'
        justifyContent='center'
        alignItems='center'
        style={{ backgroundColor: '#FFF', height: '100vh'}}
      >
        <Image
          src="/main-pic.jpg"
          alt="Main Picture"
          width={1601}
          height={800}
          layout="responsive"
          style={{ maxHeight: "80vh", maxWidth: "80vw" }}
        />
      </Grid>
    </>
  );
}
